baseURL: "https://batamladen.github.io/Dead-Pirate-Society/"
languageCode: "en-us"
title: "Dead Pirate Society"
theme: "PaperMod"
publishDir: "docs"
canonifyURLs: true

menu:
  main:

    - identifier: about
      name: About
      url: /about/
      weight: 1

    - identifier: writeups
      name: Writeups
      url: /writeups/
      weight: 2

    - identifier: members
      name: Members
      url: /members/
      weight: 3

    

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  customCSS:
    - css/custom.css