baseURL: "http://localhost:1313/"
languageCode: "en-us"
title: "Dead Pirate Society"
theme: "PaperMod"
publishDir: "docs"


menu:
  main:
    - identifier: writeups
      name: Writeups
      url: /writeup/
      weight: 1

    - identifier: members
      name: Members
      url: /members/
      weight: 2



markup:
  goldmark:
    renderer:
      unsafe: true
